---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: app
spec:
  ingressClass: nginx
  rules:
  - http:
      paths:
      - path: /cloud
        pathType: Prefix
        backend:
          serviceName: nextcloud
          servicePort: 8080
