---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: app
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /cloud
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 8080
